name: Linux ManyWheels Build

on:
 push:
 workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel pytest twine pillow

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_BUILD: cp36-manylinux_x86_64 cp36-manylinux_i686	cp37-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp38-manylinux_i686 cp39-manylinux_x86_64 cp39-manylinux_i686

      - name: Install Module for tests
        run: python setup.py install

      - name: Run tests
        run: pytest -v -s
      
      #- uses: actions/upload-artifact@v2
      #  with:
      #    path: ./wheelhouse/*.whl